CREATE TABLE `D_PESSOAIS` (
	`CONT_ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DSC_NOME` VARCHAR (40) NOT NULL,
	`DSC_EMAIL` VARCHAR (60) NOT NULL,
	`DSC_SNOME` VARCHAR (40),
	`NUM_RGIE` INT (20) NOT NULL,
	`NUM_PFPJ` INT (20) NOT NULL,
	`DSC_LOG` VARCHAR (30) NOT NULL,
	`DSC_BAIRRO` VARCHAR (25) NOT NULL,
	`DSC_COMP` VARCHAR (40),
	`NUM_NUM` INT (5) NOT NULL,
	`DSC_CID` VARCHAR (15) NOT NULL,
	`DSC_UF` VARCHAR (2) NOT NULL,
	`NUM_CEP` INT (10) NOT NULL,
	`DSC_CEMAIL` VARCHAR(60) NOT NULL,
	`DSC_CTEL` INT(20) NOT NULL,
) ENGINE = MYISAM;

CREATE TABLE C_CONTATO (
	DSC_CONNOME VARCHAR(40) NOT NULL,
	DSC_CONEMAIL VARCHAR(60) NOT NULL,
	DSC_COM VARCHAR(140) NOT NULL
) ENGINE = MYISAM;
